In [1]:
import numpy as np
import copy
from sklearn import preprocessing
import os
import pandas as pd
from matplotlib import pyplot as plt
from numpy.random import seed
from sklearn.model_selection import train_test_split,cross_val_score
from xgboost import XGBClassifier
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import QuantileTransformer

from collections import Counter
from imblearn.over_sampling import SMOTE
from sklearn.metrics import f1_score,precision_score,recall_score,roc_auc_score,accuracy_score,roc_curve
import sklearn.ensemble as se
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from xgboost import plot_importance
import matplotlib.pyplot as plt
from lightgbm.sklearn import LGBMClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from catboost import CatBoostClassifier

import seaborn as sns
%matplotlib inline
from xgboost import plot_importance
from sklearn.model_selection import learning_curve
from sklearn.model_selection import validation_curve
from sklearn.model_selection import KFold
import warnings
from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import BorderlineSMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

In [2]:
file2 = 'afterfilter.xlsx'
data = pd.read_excel(file2)

In [3]:
df = data

'Diabetes','Annual-Family-Income','X60-sec-pulse','Systolic','Diastolic',
            'Body-Mass-Index','Lymphocyte','Monocyte','Red-Blood-Cells','Hemoglobin',
             'Mean-Cell-Vol','Mean-Cell-Hgb-Conc.','Platelet-count', 'Mean-Platelet-Vol', 'Segmented-Neutrophils',
            'Red-Cell-Distribution-Width', 'ALP', 'AST', 'ALT',
            'Creatinine', 'GGT', 'Iron', 'LDH', 'Phosphorus',
            'Uric.Acid

In [4]:
y =  df['Diabetes']
x = df.drop(['Diabetes'],axis = 1)

In [5]:
from imblearn.over_sampling import ADASYN
from sklearn.datasets import make_classification

In [6]:
#######ADASYN    过采样

In [7]:
df = data
adasyn = ADASYN(sampling_strategy='auto', random_state=42)

x_balance, y_balance = adasyn.fit_resample(x, y)

X_train, X_test, y_train, y_test = train_test_split(x_balance,y_balance,test_size=0.2, random_state=42)

In [8]:
xg_model = XGBClassifier()
xg_model.fit(X_train, y_train)
xg_pred = xg_model.predict(X_test)
xg_proba=xg_model.predict_proba(X_test)
####评价指标
print(classification_report(y_test, xg_pred,digits=4))


              precision    recall  f1-score   support

           0     0.9784    0.9856    0.9820      5555
           1     0.9858    0.9786    0.9822      5657

    accuracy                         0.9821     11212
   macro avg     0.9821    0.9821    0.9821     11212
weighted avg     0.9821    0.9821    0.9821     11212



In [9]:
from sklearn.metrics import confusion_matrix
confusion_matrix(xg_pred,y_test)

array([[5475,  121],
       [  80, 5536]], dtype=int64)

In [9]:
spc = 5144/(5144+57)
spc

0.9890405691213229

In [ ]:
##########欠采样

,'Annual-Family-Income','X60-sec-pulse','Systolic','Diastolic',
            'Body-Mass-Index','Lymphocyte','Monocyte','Red-Blood-Cells','Hemoglobin',
             'Mean-Cell-Vol','Mean-Cell-Hgb-Conc.','Platelet-count', 'Mean-Platelet-Vol', 'Segmented-Neutrophils',
            'Red-Cell-Distribution-Width', 'ALP', 'AST', 'ALT',
            'Creatinine', 'GGT', 'Iron', 'LDH', 'Phosphorus',
            'Uric.Acid'

In [27]:
df = data
y =  df['Diabetes']
x = df.drop(['Diabetes'],axis = 1)

In [28]:

# 使用集成方法EasyEnsembleClassifier处理不平衡样本
from imblearn.ensemble import EasyEnsembleClassifier  # 导入简单集成方法EasyEnsembleClassifier
model_EasyEnsemble = EasyEnsembleClassifier()  # 建立EasyEnsemble模型对象
model_EasyEnsemble.fit(x, y)  # 输入数据并应用集成方法处理
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [29]:
xg_model = XGBClassifier()
xg_model.fit(X_train, y_train)
xg_pred = xg_model.predict(X_test)
xg_proba=xg_model.predict_proba(X_test)
####评价指标
print(classification_report(y_test, xg_pred,digits=4))


              precision    recall  f1-score   support

           0     0.9657    0.9960    0.9807      5548
           1     0.7284    0.2314    0.3512       255

    accuracy                         0.9624      5803
   macro avg     0.8471    0.6137    0.6659      5803
weighted avg     0.9553    0.9624    0.9530      5803



In [30]:
from sklearn.metrics import confusion_matrix
confusion_matrix(xg_pred,y_test)

array([[5526,  196],
       [  22,   59]], dtype=int64)

In [25]:
spc = 59/(59+196)
spc

0.23137254901960785

In [ ]:
######欠采样方法RandomUnderSampler

,'Annual-Family-Income','X60-sec-pulse','Systolic','Diastolic',
            'Body-Mass-Index','Lymphocyte','Monocyte','Red-Blood-Cells','Hemoglobin',
             'Mean-Cell-Vol','Mean-Cell-Hgb-Conc.','Platelet-count', 'Mean-Platelet-Vol', 'Segmented-Neutrophils',
            'Red-Cell-Distribution-Width', 'ALP', 'AST', 'ALT',
            'Creatinine', 'GGT', 'Iron', 'LDH', 'Phosphorus',
            'Uric.Acid'

In [31]:
df = data
y =  df['Diabetes']
x = df.drop(['Diabetes'],axis = 1)

In [32]:
# 使用RandomUnderSampler方法进行欠采样处理
from imblearn.under_sampling import RandomUnderSampler # 导入欠采样方法Random UnderSampler
rus = RandomUnderSampler(random_state=0) # 建立RandomUnderSampler模型对象
X_resampled, Y_resampled = rus.fit_resample(x, y) # 输入数据并进行欠采样处理
X_train, X_test, y_train, y_test = train_test_split(X_resampled,Y_resampled,test_size=0.2, random_state=42)

In [33]:
xg_model = XGBClassifier()
xg_model.fit(X_train, y_train)
xg_pred = xg_model.predict(X_test)
xg_proba=xg_model.predict_proba(X_test)
####评价指标
print(classification_report(y_test, xg_pred,digits=4))


              precision    recall  f1-score   support

           0     0.8287    0.8387    0.8337       248
           1     0.8253    0.8147    0.8200       232

    accuracy                         0.8271       480
   macro avg     0.8270    0.8267    0.8268       480
weighted avg     0.8271    0.8271    0.8270       480



In [34]:
from sklearn.metrics import confusion_matrix
confusion_matrix(xg_pred,y_test)

array([[208,  43],
       [ 40, 189]], dtype=int64)

In [35]:
spc = 189/(189+43)
spc

0.8146551724137931

SMOTE

In [39]:
df = data
y =  df['Diabetes']
x = df.drop(['Diabetes'],axis = 1)

In [40]:
x_balance,y_balance = SMOTE(random_state=42).fit_resample(x,y)
#x_balance = pd.DataFrame(x_balance)
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [41]:
xg_model = XGBClassifier()
xg_model.fit(X_train, y_train)
xg_pred = xg_model.predict(X_test)
xg_proba=xg_model.predict_proba(X_test)
####评价指标
print(classification_report(y_test, xg_pred,digits=4))


              precision    recall  f1-score   support

           0     0.9712    0.9928    0.9819      5563
           1     0.6552    0.3167    0.4270       240

    accuracy                         0.9648      5803
   macro avg     0.8132    0.6547    0.7044      5803
weighted avg     0.9581    0.9648    0.9589      5803



In [42]:
from sklearn.metrics import confusion_matrix
confusion_matrix(xg_pred,y_test)

array([[5523,  164],
       [  40,   76]], dtype=int64)

In [44]:
spc = 76/(76+164)
spc

0.31666666666666665